# Generated by Django 6.0.4 on 2026-04-29 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=50)),
                ('shift', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='messlog',
            old_name='check_in_time',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='fine',
            name='imposed_date',
        ),
        migrations.RemoveField(
            model_name='fine',
            name='status',
        ),
        migrations.RemoveField(
            model_name='mealrate',
            name='effective_from',
        ),
        migrations.RemoveField(
            model_name='mealrate',
            name='effective_to',
        ),
        migrations.RemoveField(
            model_name='messlog',
            name='check_out_time',
        ),
        migrations.RemoveField(
            model_name='messlog',
            name='date',
        ),
        migrations.RemoveField(
            model_name='messoffrequest',
            name='approval_date',
        ),
        migrations.RemoveField(
            model_name='messoffrequest',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='messoffrequest',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='messoffrequest',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='messoffrequest',
            name='requested_at',
        ),
        migrations.RemoveField(
            model_name='monthlybill',
            name='breakfast_count',
        ),
        migrations.RemoveField(
            model_name='monthlybill',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='monthlybill',
            name='dinner_count',
        ),
        migrations.RemoveField(
            model_name='monthlybill',
            name='lunch_count',
        ),
        migrations.RemoveField(
            model_name='monthlybill',
            name='status',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='student',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='monthlybill',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mealrate',
            name='meal_type',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='messlog',
            name='meal_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='messoffrequest',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
